"""
Django settings for proyUA project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
#from decouple import config, Csv
import mimetypes
mimetypes.add_type("text/css", ".css", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)7dphhnlgk0qwj9cq(p)jk7cbr5g+3dveadyc=!rafa2$z^cy2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','díaua-do.org','54.226.67.132',]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # plugins
    'six',
    'import_export',
    'storages',
    'django_filters',
    'crispy_forms',
    'bootstrap4',
    'crispy_bootstrap4',
    
    # apps
    'appUA',
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proyUA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(STATIC_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "proyUA.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
keepalive_kwargs = {
    "keepalives": 1,
    "keepalives_idle": 240,
    "keepalives_interval": 30,
    "keepalives_count": 15,
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'diaua_bd',
        'HOST': 'localhost', #recomendacion bitname => '/opt/bitnami/postgresql',
        'PORT': '5432',
        'USER': 'diaau_usuario',
        'PASSWORD': 'diaauAdm#123!',
        'CONN_MAX_AGE': 600,
        **keepalive_kwargs
    },
    "sqlite3": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

#Admin 
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False
IMPORT_EXPORT_CHUNK_SIZE = 100


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-do'
LANGUAGES = (
    ('es-do', 'Español'),
    ('es', 'Español'),
    ('en', 'English'),
)

USE_TZ = True

TIME_ZONE = 'America/Santo_Domingo'

DATE_FORMAT = '%Y-%m-%d'
DATE_INPUT_FORMATS = ['%Y-%m-%d']
USE_I18N = True

USE_L10N = True

DECIMAL_SEPARATOR = '.'

THOUSAND_SEPARATOR = ','


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_ROOT = os.path.join(STATIC_DIR, 'media')
STATIC_ROOT = STATIC_DIR

STATICFILES_DIRS = [
    os.path.join(STATIC_DIR, 'media'),
    os.path.join(STATIC_DIR, 'templates'),
]

TEMPLATE_DIR = os.path.join(STATIC_DIR, 'templates')

ADMIN_MEDIA_PREFIX = os.path.join(STATIC_DIR, 'admin')

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# settings.py (Fragmento relevante)
'''
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Simula el envío
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
'''

EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER='osvaldo.larancuent@gmail.com'
EMAIL_HOST_PASSWORD='rcun vdrt azap zejx'
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_USE_SSL=False
ADMIN_USER_NAME='o.larancuent'
ADMIN_USER_EMAIL='osvaldo@localhost'

MANAGERS=[]
ADMINS=[]
if all([ADMIN_USER_NAME, ADMIN_USER_EMAIL]):
    ADMINS +=[
        (f'{ADMIN_USER_NAME}', f'{ADMIN_USER_EMAIL}')
    ]
    MANAGERS=ADMINS